[package]
name = "virtualdesign0/garbageman"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
	"src/GarbageMan",
	"default.project.json",
	"README.md",
	"BENCHMARKS.md",
	"ROJO_WALLY.md",
	"wally.toml",
]
exclude = [
	"tests",
	"benchmarks",
	"benchmark.project.json",
]

[dependencies]
